config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'home/index'
  root 'home#index'
  
  resources :containers do
    resources :container_histories, only: [:index], path: 'history'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/container.rb
class Container < ApplicationRecord
  HISTORY_INTERVAL_TIME = 5.minutes

  has_many :container_histories

  has_secure_token :sensor_token
  
  validates :name, presence: true

  # En base al porcentaje actual obtenemos los litros actuales
  def current_capacity_liters
    if self.high_capacity && self.current_capacity_percentage
      liters = self.current_capacity_percentage.to_f / 100 * self.high_capacity
      return liters.to_i
    end

    return nil
  end

  # Obtenemos el porcentaje de liquido actual
  def current_capacity_percentage
    if self.low_sensor and self.high_sensor and self.last_sensor
      range = self.low_sensor - self.high_sensor
      percentage = (self.low_sensor - self.last_sensor) / range.to_f * 100
      return percentage.to_i
    end

    return nil
  end

  # Crea un registro para el historial solo si el valor actual exede 5 minutos de la ultima historia
  def save_history
    if( self.container_histories.count == 0)
      self.container_histories.create(sensor_value: self.last_sensor, capacity_percentage: self.current_capacity_percentage)
    # Creación de la primera historia, asi el IF funciona
    elsif( self.contact_sensor_at - self.container_histories.last.created_at) > HISTORY_INTERVAL_TIME
      self.container_histories.create(sensor_value: self.last_sensor, capacity_percentage: self.current_capacity_percentage)
    end
  end

end

app/models/container_history.rb
class ContainerHistory < ApplicationRecord
  belongs_to :container
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # skip_before_action :verify_authenticity_token, if: :json_request?if: :json_request?
  skip_before_action :verify_authenticity_token, only: [:update]

  def json_request?
    request.format.json?
  end
end

app/controllers/container_histories_controller.rb
class ContainerHistoriesController < ApplicationController
  before_action :set_container_with_history, only: [:index]

  def index
    @container_histories = @container.container_histories
  end

  private

  def set_container_with_history
    @container = Container.find(params[:container_id])
  end
end

app/controllers/containers_controller.rb
class ContainersController < ApplicationController
  before_action :set_container, only: [:show, :edit, :update, :destroy]

  # GET /containers
  # GET /containers.json
  def index
    @containers = Container.all
  end

  # GET /containers/1
  # GET /containers/1.json
  def show
  end

  # GET /containers/new
  def new
    @container = Container.new
  end

  # GET /containers/1/edit
  def edit
  end

  # POST /containers
  # POST /containers.json
  def create
    @container = Container.new(container_params)

    respond_to do |format|
      if @container.save
        format.html { redirect_to @container, notice: 'Container was successfully created.' }
        format.json { render :show, status: :created, location: @container }
      else
        format.html { render :new }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /containers/1
  # PATCH/PUT /containers/1.json
  def update
    @container.contact_sensor_at = Time.now if container_params[:last_sensor].present?

    respond_to do |format|
      if @container.update(container_params)
        @container.save_history if container_params[:last_sensor].present?
        format.html { redirect_to @container, notice: 'Container was successfully updated.' }
        format.json { render :show, status: :ok, location: @container }
      else
        format.html { render :edit }
        format.json { render json: @container.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /containers/1
  # DELETE /containers/1.json
  def destroy
    @container.destroy
    respond_to do |format|
      format.html { redirect_to containers_url, notice: 'Container was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_container
      @container = Container.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def container_params
      params.require(:container).permit(:name, :address, :location, :state, :lat, :long, :last_sensor, :high_sensor, :low_sensor, :high_capacity, :low_capacity)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @containers = Container.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/containers_helper.rb
module ContainersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/container_histories/index.html.erb
<div class="container">
  
  <h1><i><%= @container.name %></i> - Container history</h1>
  <div id="container_histories">

    <div class="chart">
      <h3>Última hora</h3>
      <%= area_chart @container.container_histories.where(created_at: (Time.now - 1.hour)..Time.now).group_by_minute(:created_at).average(:capacity_percentage), height: "200px" %>
    </div>

    <div class="chart">
      <h3>Último día</h3>
      <%= area_chart @container.container_histories.where(created_at: (Time.now - 1.day)..Time.now).group_by_minute(:created_at).average(:capacity_percentage), height: "200px" %>
    </div>

    <div class="chart">
      <h3>Última Semana</h3>
      <%= area_chart @container.container_histories.where(created_at: (Time.now - 1.week)..Time.now).group_by_day(:created_at).average(:capacity_percentage), height: "200px" %>
    </div>

    <div class="chart">
      <h3>Último Mes</h3>
      <%= area_chart @container.container_histories.where(created_at: (Time.now - 1.month)..Time.now).group_by_day(:created_at).average(:capacity_percentage), height: "200px" %>
    </div>

    <div class="chart">
      <h3>Último Año</h3>
      <%= area_chart @container.container_histories.where(created_at: (Time.now - 1.year)..Time.now).group_by_week(:created_at).average(:capacity_percentage), height: "200px" %>
    </div>

    <table class="table">
      <thead>
        <th width="150">Datetime</th>
        <th width="100">S. dist.</th>
        <th witdh="100">Capacity%</th>
      </thead>
      <tbody>
        <% @container.container_histories.each do |history| %>
          <tr class="history">
            <td><%= history.created_at %></td>
            <td><%= history.sensor_value %> cm</strong></td>
            <td><%= history.capacity_percentage %> %</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/containers/_form.html.erb
<div class="row">
  <div class="col-sm-12 col-md-6 col-lg-3">
    
  
    <%= form_with(model: container, local: true) do |form| %>
      <% if container.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(container.errors.count, "error") %> prohibited this container from being saved:</h2>

          <ul>
          <% container.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= form.label :name, 'Nombre' %>
        <%= form.text_field :name, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :address, 'Dirección' %>
        <%= form.text_field :address, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :location, 'Localidad' %>
        <%= form.text_field :location, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :state, 'Estado' %>
        <%= form.text_field :state, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :lat, 'Latitud' %>
        <%= form.text_field :lat, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :long, 'Longitud' %>
        <%= form.text_field :long, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :high_sensor, 'Maxima del sensor (cm)' %>
        <%= form.number_field :high_sensor, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :low_sensor, 'Minima del sensor (cm)' %>
        <%= form.number_field :low_sensor, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :high_capacity, 'Maxima Capacidad (lts)' %>
        <%= form.number_field :high_capacity, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :low_capacity, 'Minima Capacidad (lts' %>
        <%= form.number_field :low_capacity, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit class: 'btn btn-primary' %>
      </div>
    <% end %>

  </div>
</div>

app/views/containers/edit.html.erb
<div class="container">
	
	<h1>Editando Contenendor</h1>

	<%= render 'form', container: @container %>

	<%= link_to 'Ver', @container %> |
	<%= link_to 'Regresar', containers_path %>
</div>

app/views/containers/index.html.erb
<div class="container">
  
  <p id="notice"><%= notice %></p>

  <h1>Contenedores</h1>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Dirección</th>
        <th>Localidad</th>
        <th>Estado</th>
        <th>Latitud</th>
        <th>Longitud</th>
        <th>Ultimo val sensor</th>
        <th>Max. sensor</th>
        <th>Min. sensor</th>
        <th>Max capacidad</th>
        <th>Min capacidad</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @containers.each do |container| %>
        <tr>
          <td><%= container.name %></td>
          <td><%= container.address %></td>
          <td><%= container.location %></td>
          <td><%= container.state %></td>
          <td><%= container.lat %></td>
          <td><%= container.long %></td>
          <td><%= container.last_sensor %></td>
          <td><%= container.high_sensor %></td>
          <td><%= container.low_sensor %></td>
          <td><%= container.high_capacity %></td>
          <td><%= container.low_capacity %></td>
          <td><%= link_to 'Ver', container, class: 'btn btn-sm btn-info' %></td>
          <td><%= link_to 'Editar', edit_container_path(container), class: 'btn btn-sm btn-warning' %></td>
          <td><%= link_to 'Eliminar', container, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to '+ Nuevo contenedor', new_container_path, class: 'btn btn-primary' %>
</div>

app/views/containers/new.html.erb
<h1>New Container</h1>

<%= render 'form', container: @container %>

<%= link_to 'Back', containers_path %>

app/views/containers/show.html.erb
<div class="container">
  
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Nombre:</strong>
    <%= @container.name %>
  </p>

  <p>
    <strong>Dirección:</strong>
    <%= @container.address %>
  </p>

  <p>
    <strong>Localidad:</strong>
    <%= @container.location %>
  </p>

  <p>
    <strong>Estado:</strong>
    <%= @container.state %>
  </p>

  <p>
    <strong>Latitud:</strong>
    <%= @container.lat %>
  </p>

  <p>
    <strong>Longitud:</strong>
    <%= @container.long %>
  </p>
  <p><a href="https://google.com/maps/@<%= @container.lat %>,<%= @container.long %>,21z" target="_blank" class="btn btn-sm btn-outline-success">Ver en Google Maps</a></p>

  <p>
    <strong>Ultima Lectura Sensor:</strong>
    <%= @container.last_sensor || '*Not defined*' %>
    cm
  </p>
  <p><i><strong><%= @container.current_capacity_percentage %> % capacity</strong></i></p>

  <p>
    <strong>Max. sensor:</strong>
    <%= @container.high_sensor || '*Not defined*' %>
    cm
  </p>

  <p>
    <strong>Min. sensor:</strong>
    <%= @container.low_sensor || '*Not defined*' %>
    cm
  </p>

  <p>
    <strong>Max. capacidad:</strong>
    <%= @container.high_capacity %>
    liters
  </p>

  <p>
    <strong>Min. capacidad:</strong>
    <%= @container.low_capacity %>
    liters
  </p>

  <p>
    <strong>Token del Sensor</strong>
    <%= @container.sensor_token %>
  </p>

  <p>
    <strong>Ultimo contacto con el sensor:</strong>
    <%= @container.contact_sensor_at %>
  </p>

  <p><strong>Click para <%= link_to 'Ver Historial del Contenedor', container_container_histories_path(@container), class: 'btn btn-info' %></strong></p>

  <%= link_to 'Editar', edit_container_path(@container) %> |
  <%= link_to 'Regresar', containers_path %>
</div>

app/views/home/index.html.erb
<div class="container">
  
  <h1>Inicio Wazzlo</h1>
  <p>Toma el control de contenedores de agua, como cisternas, tinacos y otros.</p>

  <section>
    <div>
      <h5>Dispositivos actuales:
        <span class="badge badge-info"><%= @containers.count %></span><i> <%= link_to 'ver todos', containers_path, class: 'btn btn-sm btn-outline-primary' %></i>
      </h5>
    </div>
    <br>

    <hr>

    <h2>Deberias echar un vistazo a estos contenedores</h2>
    <div id="home_devices">
      <% if @containers.count == 0 %>
        <p>Aun no tienes ningún dispositivo que mostrar. Da click para <%= link_to 'agregar un dispositivo nuevo', new_container_path %>.</p>
      <% else %>
        <% @containers.each do |container| %>
          <div class="item">
            <div class="title">
              <%= link_to container.name, container_path(container) %>
              
            </div>
            <div class="left">
              <p><i><strong><%= container.current_capacity_percentage %> % capacity</strong></i></p>
              <p><i><strong><%= container.current_capacity_liters %> lt</strong> / <%= container.high_capacity %></i></p>
            </div>
            <div class="right">
              Last contact <%= time_ago_in_words container.contact_sensor_at if container.contact_sensor_at %>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wazzlo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <ul>
          <li><%= link_to 'Inicio', root_path, class: "#{'active' if controller_name == 'home'}" %></li>
          <li><%= link_to 'Contenedores', containers_path, class: "#{'active' if controller_name == 'containers'}" %></li>
        </ul>
      </nav>
    </header>

    <%= yield %>
  </body>
</html>

app/views/water_devises/_form.html.erb
<%= form_with(model: water_devise, local: true) do |form| %>
  <% if water_devise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(water_devise.errors.count, "error") %> prohibited this water_devise from being saved:</h2>

      <ul>
      <% water_devise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :lat %>
    <%= form.text_field :lat %>
  </div>

  <div class="field">
    <%= form.label :long %>
    <%= form.text_field :long %>
  </div>

  <div class="field">
    <%= form.label :current_value %>
    <%= form.text_field :current_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>